### ISSUE TITLE
panic:cannot intersect: ^18 && ^16

### ISSUE THREAD

**Issue by dcvz** [pkgxdev/pkgx#683]
In a javascript project I'm attempting to have a `tea.yaml` with the following contents:
```
dependencies:
  classic.yarnpkg.com: ^1.22
```

This is so the environment recognizes which yarn I want to use, however when I try to sync the env using `tea -SE && cd .` I get the following crash:
```
Error: cannot intersect: ^18 && ^16
    at Module.intersect (https://deno.land/x/libtea@v0.10.7/src/utils/semver.ts:349:32)
    at condense (https://deno.land/x/libtea@v0.10.7/src/plumbing/hydrate.ts:87:39)
    at hydrate (https://deno.land/x/libtea@v0.10.7/src/plumbing/hydrate.ts:13:17)
    at default (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/0500470f/src/prefab/install.ts:24:40)
    at default (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/0500470f/src/prefab/setup.ts:94:44)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async run (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/0500470f/src/app.main.ts:44:63)
    at async file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/0500470f/src/app.ts:23:5
```

**Comment by jhheider** [comment]
Hm, `classic.yarnpkg.com` depends on `nodejs.org: >=5`. Anything else in your tea.yml? Are you comfortable posting your package.json? I know @mxcl was looking to make it parse the `engines:` key, in addition to the `tea:` key.

Failing that, `DEBUG=1 tea -E` might help.

**Comment by jhheider** [comment]
I wouldn't be surprised if the latter problem is related to https://github.com/teaxyz/cli/issues/681

**Comment by mxcl** [comment]
I can't trace a way `nodejs.org^18` gets added to the env. I'm hoping this is also fixed in v1 since we don’t magically add developer environments anymore and you have to opt in.

**Comment by mxcl** [comment]
closing, but reopen if not fixed

**Comment by amok** [comment]
@mxcl the issue is still reproducible

I did a little of debugging 

1) pkgx add `node@16` to deps (basing on .node-version etc)

2) pkgx adds `yarnpkgs.com@*` to the deps
https://github.com/pkgxdev/pkgx/blob/104affb636a128b9e9c6b7fb2f07f2f0ea17f128/src/utils/devenv.ts#L80-L82

3) Later pkgx resolves `yarnpkgs.com@*`' deps by looking in its package.yml

https://github.com/pkgxdev/pantry/blob/ed7abb2aa6fbae733e3ac7857280b2801e5905f2/projects/yarnpkg.com/package.yml#L12-L14
![image](https://github.com/pkgxdev/pkgx/assets/1369559/c582d99d-c6c8-47b7-9a32-a4a28ccb2a24)

4)  pkgx throws validation deps' versions intersection

See https://github.com/pkgxdev/libpkgx/blob/main/src/plumbing/hydrate.ts#L64-L66

![image](https://github.com/pkgxdev/pkgx/assets/1369559/bd3ccce7-7f22-4b63-b813-5836c63b36ce)

**Comment by amok** [comment]
@mxcl you should be able to reproduce the bug by executing

```bash
env +node@16 +yarnpkg.com
```

**Comment by jhheider** [comment]
it looks like yarn/berry actually requires node >=18.12.0: https://github.com/yarnpkg/berry/blob/580f593db4ab592bfff2d9fd5c5613c29c6fee2b/package.json#L77-L79

so, it's definitely a problem with the auto-adding. specifically, because yarnv1 and yarn/berry are very very different. one possible solution that likely _wouldn't fix_ this problem is https://github.com/pkgxdev/libpkgx/discussions/67. But, the better option is to probably be more conservative with yarn injections (and not do them at all).
